# Generated by Django 2.0.3 on 2018-03-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.EmailField(help_text='Enter your email id', max_length=20)),
                ('password', models.CharField(help_text='Should consist of alphabets and digits', max_length=20)),
            ],
            options={
                'ordering': ['-Username'],
            },
        ),
    ]
