# Generated by Django 2.0.3 on 2018-04-01 11:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180401_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Allergy', models.CharField(max_length=20, null=True)),
                ('Disease', models.CharField(max_length=20, null=True)),
                ('Fruits', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=20, null=True), size=None)),
                ('Vegetables', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='0', max_length=20, null=True), size=None)),
                ('Dairy', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', max_length=20), default=list, null=True, size=None), size=None)),
                ('Nuts', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', max_length=20), default=list, null=True, size=None), size=None)),
            ],
            options={
                'ordering': ['-Allergy'],
            },
        ),
    ]
