# Generated by Django 2.0.3 on 2018-04-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_details_nutritionsuggestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
        migrations.DeleteModel(
            name='NutritionSuggestion',
        ),
        migrations.AddField(
            model_name='health',
            name='age',
            field=models.IntegerField(default=1, help_text='Enter your age :'),
        ),
        migrations.AddField(
            model_name='health',
            name='allergy',
            field=models.TextField(help_text='Enter your allergy :', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='disease',
            field=models.TextField(help_text='Enter the disease :', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='name',
            field=models.CharField(help_text='Enter your name :', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='phonenumber',
            field=models.IntegerField(default=1, help_text='Enter your phonenumber :'),
        ),
        migrations.AlterField(
            model_name='health',
            name='password',
            field=models.CharField(help_text='Should consist of alphabets and digits', max_length=20, null=True),
        ),
    ]
